### ISSUE TITLE
BBBB: nltools::messaging on BBB not working properly

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1047]
Using the logs I could pinpoint that the static variable *signals* is empty when execution enters  nltools::msg::detail::notifyClients. I did log that prior to that the signals have been registered and persisted over multiple receive<FooBar> calls.

The reason for that has not yet been identified. I'm not able to reproduce that behavior on the developer machine.

Next tests will include running the bbbb on the device and an playground locally.

**Comment by schlenkibus** [comment]
@hhoegelo What do you think about that observed behavior?

**Comment by schlenkibus** [comment]
Maybe we should check the parsing of messages for UB?

**Comment by hhoegelo** [comment]
I think the problem is in bbbb, Application-ctor: The bridges are created in the init block. They finally connect to the signals in question. Later, in the constructor body, setupMessaging() is called. The nltools::msg::init(conf) call will at first call msg::deInit(), clearing the signals map.

I suggest to move msg-initialization code into initStatic(), which exists exactly for the reason, that some things have to be done before the application can be constructed.
