### ISSUE TITLE
UI (Panel-Unit) : Cannot Create Preset when there are no Banks/Presets

### ISSUE THREAD

**Issue by KlausStrohhaecker** [nonlinear-labs-dev/C15#1451]
Using the Panel-Unit for UI, one cannot create a new preset when there are no banks/presets. "Store" button does nothing.
Using Web-UI all is fine (an intital preset can be always created).
PG : NAMM 1.7 Preview, afcb7fd (3001)

**Comment by MatthiasSeeber** [comment]
This is due to the fact that there are no Banks present. When selecting Bank Mode and creating a new Bank (Edit -> New), then stroring will be possible.

It would be useful to show an error message on the BOLED (like "Please create a Bank first"), or, even better, automate the creation of a new Bank when storing a Preset with no Banks present.

**Comment by schlenkibus** [comment]
@nonlinear-labs Which of the 2 options Matthias suggested do you prefer?
