### ISSUE TITLE
OLED messages on power up/down non existent

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1510]
After the update to the current 'Master', the C15 does not show messages such as 
'initializing...', 'exiting UI...' or 'shutting down...'
These scripts are now stored under
/usr/C15/scripts/soled-boot-message.sh ... -exit-PG-message.sh ... -shutdown-message.sh
and not linked to any procedure in terms of power up or down.
Can we invoke these via ssh maybe?

**Comment by KlausStrohhaecker** [comment]
1) 'initializing...' and 'shutting down...' are called low-level from /lib/systemd/system/systemd-modules-load.service and /lib/systemd/system/systemd-poweroff.service, locally on the BBB. I see no reason why this should change as the BBB is the first interface layer to the UI. The more local this is and the less dependant on anything else, the better (for example, moving it to the bridge wouldn't be a good idea, also for timing issues -- the init message shall display right after the ESPI-driver is initialized).

So all that's required is to adapt the calls in these services pointing to the correct place:
"ExecStart=-/nonlinear/scripts/soled-boot-message.sh"
-->
"ExecStart=-/usr/C15/scripts/soled-boot-message.sh"
in both system scripts (note the "-" character).

IMPORTANT: All scripts from /nonlinear/scripts/ need to be checked for subroutine calls with absolute paths, btw.


2) For the 'exiting UI...' message called in the playground.service, this has been a workaround only, from the beginning.
Best way to fix is this message being moved to the playground's native exit code, together with setting all LEDs (PanelUnit and Ribbons) to "ON" while we're at it.

NOTE: The "termination timeout" issue should also be dealt with now that we can debug the PG code in the target system, see https://github.com/nonlinear-labs-dev/C15/issues/1080


3) Further, there is a 'backup-presets.sh" called after the playground has ended. Again, this was only a makeshift solution.
The idea is that the user presets are copied to a removable media, the micro-SD card, so that if a C15 blows up completely and the BBB is severely broken or destroyed, user data still might be retreived from the SD-card.

With the PG moving to the ePC, the backup function should also move to there, saving presets (and any other user data/settings, and maybe several levels deep). The physical media will remain to be the SD-Card on the BBB hardware because all installed C15's don't have an SD-Card fitted on the ePC, if even possible.
Therefore, the function must be proxied to the BBB in some way, maybe just a simple SSH call.

Probably we might need a sort of proxied plaground service anyway to avoid data loss and possible race conditions. The shutdown sequence must remain well ordered and synced between ePC and BBB.

**Comment by hhoegelo** [comment]
@KlausStrohhaecker This is still in progress and on my radar.

**Comment by hhoegelo** [comment]
I am working on the features mentioned by @KlausStrohhaecker.
There is one feature I would like to drop:

"... there is a 'backup-presets.sh" called after the playground has ended. Again, this was only a makeshift solution.The idea is that the user presets are copied to a removable media, the micro-SD card, so that if a C15 blows up completely and the BBB is severely broken or destroyed, user data still might be retreived from the SD-card..."

I think this makes things complicated and introduces run-time dependencies and race conditions for little revenue: Is there a reason to believe that the SD-Card plugged into the BBB is more reliable than the SSD attached on the ePC? Both media can not be accessed from outside without tools. On the other hand, if you can still log onto BBB, it should be possible to log onto ePC.

@nonlinear-labs What do you think?
