### ISSUE TITLE
BBB: SD dependency 

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1712]
We should focus on deploying "rootfs" on the internal flash of the BBB and cut the SD dependency.
We should also discuss whether, we should maintain the extra partition, which allows to boot from USB-Stick and how it can be part of the new BBB image. 

### current state of affairs (2020-10-01 KSTR)
- booting from internal flash (eMMC) is working fine and the setup to do so (clone the system from SD-card to flash and make it bootable) is actually quite simple.
- a problem pops up when we want to boot from eMMC when an SD-card is still inserted. It turns out that the low-level bootloaders cannot handle an inserted SD-card which does *not* have a proper linux boot config, that is no /boot/uImage file in a (linux) file system on any of its partitions. The problem only shows up with out proprietary bootloader, the stock bootloader simply ignores 'invalid' SD-card content. To fix this we'd have to start here: https://github.com/nonlinear-labs-dev/u-boot/commit/3fde2563258ae1f488ee737168f69f2c7cf51e61
- I also found a lot of confusion, many files both on the SD-card and the eMMC that look to responsible for booting and loading our device tree actually are not, etc. Looks like the only relevant information is *hardcoded* in the second stage bootloader (u-boot.img) which resides in the partition section of the eMMC, see above.

**Comment by KlausStrohhaecker** [comment]
### Boot Sequencing

From the following section of the BBB User Manual seems to follow that once a running OS is present on the internal flash (eMMC on MMC1) the BBB will not try to boot from the microSD-Card (unless the boot button on the BBB PCB is pressed):
![grafik](https://user-images.githubusercontent.com/42267360/94561069-d005f000-0263-11eb-9bda-c537b07cf73b.png)

This conflicts with the actual experience where a stock BBB with the Debian distro on the eMMC DOES boot from the microSD-Card when present.


### Early boot messages of a virgin BBB when booting from internal flash:
```
U-Boot SPL 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15)
Trying to boot from MMC
bad magic


U-Boot 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15 -0500), Build: jenkins-github_Bootloader-Builder-351

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
Card did not respond to voltage select!
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
Card did not respond to voltage select!
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
1336 bytes read in 14 ms (92.8 KiB/s)
Loaded environment from /boot/uEnv.txt
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.9-ti-r25 ...
7833256 bytes read in 445 ms (16.8 MiB/s)
loading /boot/dtbs/4.4.9-ti-r25/am335x-boneblack.dtb ...
60958 bytes read in 27 ms (2.2 MiB/s)
loading /boot/initrd.img-4.4.9-ti-r25 ...
4761957 bytes read in 277 ms (16.4 MiB/s)
debug: [console=ttyO0,115200n8 root=UUID=35e81614-f61d-4801-8d2a-96ca1367f800 ro rootfstype=ext4 rootwait coherent_pool=1M quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:48a965 0x88000000] ...
Kernel image @ 0x82000000 [ 0x000000 - 0x7786a8 ]
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fb75000, end 8ffff965 ... OK
   Loading Device Tree to 8fb63000, end 8fb74e1d ... OK

Starting kernel ...
[...]
```


### Early boot messages of a virgin BBB when booting from microSD:
```
U-Boot SPL 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15)
Trying to boot from MMC
bad magic


U-Boot 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15 -0500), Build: jenkins-github_Bootloader-Builder-351

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
reading uEnv.txt
329 bytes read in 4 ms (80.1 KiB/s)
gpio: pin 55 (gpio 55) value is 1
Loaded environment from uEnv.txt
Importing environment from mmc ...
Checking if uenvcmd is set ...
gpio: pin 56 (gpio 56) value is 1
Running uenvcmd ...
4679280 bytes read in 272 ms (16.4 MiB/s)
32716 bytes read in 14 ms (2.2 MiB/s)
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:   Linux-4.4.50
   Created:      2017-11-23  12:53:42 UTC
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4679216 Bytes = 4.5 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Kernel Image ... OK
   Loading Device Tree to 8fff5000, end 8fffffcb ... OK

Starting kernel ...
[...]
```

Of course this is not actually bad as we can easily boot from an emergency SD-card in case the BBB is bricked. Otherwise we would have to rely on the u-boot patch to boot an emergency system from an attached USB-stick. Still it would be nice to know why it does not behave as described in the docs.

**Comment by KlausStrohhaecker** [comment]
In a first naiive effort I copied the SD-card with rsync to the partition where the stock linux is placed. This failed for reasons I fail to understand, see boot log:
```
U-Boot SPL 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15)
Trying to boot from MMC
bad magic


U-Boot 2016.03-00001-gd12d09f (Mar 17 2016 - 16:16:15 -0500), Build: jenkins-github_Bootloader-Builder-351

       Watchdog enabled
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

Net:   <ethaddr> not set. Validating first E-fuse MAC
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
Card did not respond to voltage select!
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
Card did not respond to voltage select!
Card did not respond to voltage select!
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mmc 1:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc1(part 0) is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
** Invalid partition 2 **
** Invalid partition 3 **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
## Error: "bootcmd_nand0" not defined
cpsw Waiting for PHY auto negotiation to complete......... TIMEOUT !
BOOTP broadcast 1
[...]
```

In Nonlinux, there is no uEnv.txt neither in / nor in /boot, instead it is located in /root.
OK, lets copy and inspect uEnv.txt and see if changes need to be applied there
Original uEnv.txt (Nonlinux on SD-Card), with line-breaks for clarity:
```
uenvcmd=mmc rescan; load mmc 1:2 ${loadaddr} boot/uImage; 
  load mmc 1:2 ${fdtaddr} boot/nonlinear-labs-2D.dtb;
  setenv mmcroot /dev/mmcblk0p2 ro;
  setenv mmcrootfstype ext4 rootwait;
  setenv bootargs console=${console} ${optargs} root=${mmcroot} rootfstype=${mmcrootfstype};
  bootm ${loadaddr} - ${fdtaddr}
  uname_r=nonlinear
uname_boot=mmc rescan;
  load mmc 1:2 ${loadaddr} boot/uImage;
  load mmc 1:2 ${fdtaddr} boot/nonlinear-labs-2D.dtb;
  setenv mmcroot /dev/mmcblk0p2 ro;
  setenv mmcrootfstype ext4 rootwait;
  setenv bootargs console=${console} ${optargs} root=${mmcroot} rootfstype=${mmcrootfstype};
  bootm ${loadaddr} - ${fdtaddr}
```
We see it accesses mmc 1:2 while the internal flash is mmc 1:1 (not sure about the nomenclature here as the boot log shows different ID's).
After changing these entries, and changing `setenv mmcroot /dev/mmcblk0p2 ro;` to `setenv mmcroot /dev/mmcblk1p1 ro;`, we should be ready to go.... well, almost. Kernel image is now found and starts to boot, but the kernel then stalls with
`[    1.963154]Waiting for root device /dev/mmcblk1p1...`

Fiddling around with the file system location turns out that this must be set to `/dev/mmcblk0p1`, which seems to mean "1st partition of the first mmc that was found" (as there is no SD card ID is 0).

### First step mastered: copy our OS to internal flash and make it boot. This of course was with a virgin beagle-bone with the stock linux in place.
The relevant changes for this:
1 - move uEnv.txt from /root to /boot
2 - edit uEnv.txt to read (remove line-breaks in each section!):
```
uenvcmd=mmc rescan; load mmc 1:2 ${loadaddr} boot/uImage; 
  load mmc 1:1 ${fdtaddr} boot/nonlinear-labs-2D.dtb;
  setenv mmcroot /dev/mmcblk0p1 ro;
  setenv mmcrootfstype ext4 rootwait;
  setenv bootargs console=${console} ${optargs} root=${mmcroot} rootfstype=${mmcrootfstype};
  bootm ${loadaddr} - ${fdtaddr}
  uname_r=nonlinear
uname_boot=mmc rescan;
  load mmc 1:1 ${loadaddr} boot/uImage;
  load mmc 1:1 ${fdtaddr} boot/nonlinear-labs-2D.dtb;
  setenv mmcroot /dev/mmcblk0p2 ro;
  setenv mmcrootfstype ext4 rootwait;
  setenv bootargs console=${console} ${optargs} root=${mmcroot} rootfstype=${mmcrootfstype};
  bootm ${loadaddr} - ${fdtaddr}
```
### As we need our emergency boot manager in order to boot from external USB, the next step is to get a preconfigured BBB to boot from eMMC which has the boot manager installed and the eMMC already formatted and partitioned (for the legacy use of the eMMC to store C15 preset data etc).

**Comment by KlausStrohhaecker** [comment]
First checks seem to indicate that the required steps do not change at all, system boots fine from eMMM with out bootmanager installed and still boots from USB stick, as well as from SD-card.

**Comment by KlausStrohhaecker** [comment]
Double checking with the stock bootloader does not show the problem. When an SD-card is inserted with no content, the system simply ignores it and boots correctly.

It might be that this is all just a simple enumeration problem, that is the loaded kernel is told where to find the file system, and that is indicated by a simple numbering scheme of the drives and partions which dynamically changes whether SD-card is preset or not.

**Comment by AntonSchmied** [comment]
However, we're now facing the following problem (rootfs on the internal flash)
```
[  252.538764] lpc_bb_driver_package_parse() : RX buffer full, dropping packets...
[  254.149098] lpc_bb_driver_package_parse() : ... missed 16 packets. RX buffer now accepting packets again.
[  262.016695] lpc_bb_driver_read() : interrupted during read, clearing remaining buffer
[  269.998421] lpc_bb_driver_read() : interrupted during read, clearing remaining buffer
```
Someone's (BBB) really overwhelmed here ...
