### ISSUE TITLE
BOLED: Sound screens open on convert

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#1753]
even when converted via webui the hwui focus is being set to sound, is this desired behaviour? @nonlinear-labs

**Comment by nonlinear-labs** [comment]
I think this detail was never specified. But it is okay to put the focus on the Sound after a Convert operation, because it is for sure something to do there after a conversion.

Probably it would be more consistent to have the same effect from the HWUI to the WebUI. If one of the other tabs is already open on the WebUI, a conversion in the HWUI would open the Sound tab in the WebUI.
