### ISSUE TITLE
AudioEngine - Glitches

### ISSUE THREAD

**Issue by hhoegelo** [nonlinear-labs-dev/C15#1782]
Our audio-engine suffers from buffer underruns from time to time. This does only happen on old generation ePC hardware (5er) and does not on new one (7er). The problem did not exist on Release-1.5, but it does exist in Release-1.7.

Here in this issue, we want to list and answer all open questions in order to isolate the problem.

- [x] Does the problem exist, even though the playground is not running on ePC? -> Yes
- [x] Do underruns occur with CPUBurningSynth as well? -> Yes
- [x] Do underruns occur with CPUBurningSynth and no playground running? -> Takes a while, but Yes
- [x] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although LPC sends no MIDI to AudioEngine? -> Yes
- [x] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although Playground sends no WebSocket to AudioEngine? -> Yes, see bullet 3
- [x] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although Playground sends no WebUI stuff? -> Yes, see bullet 3
- [x] **Do underruns occur with AudioEngine 1.7, although all WebSocket-related code is deactivated? -> Yes : AudioEngine running, playground switched off, LPC MIDI code commented out, AudioEngine- setupMessaging commented out) !!!11elf**
- [x] Do underruns occur with CPUBuringSynth and no midi in and no heartbeat? -> Yes

**Comment by hhoegelo** [comment]
@nonlinear-labs @MatthiasSeeber @schlenkibus @KlausStrohhaecker 
Please add tasks / questions to the list.

**Comment by MatthiasSeeber** [comment]
It could be helpful trying to disable sending of data as well.
- [ ] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although LPC sends no MIDI to AudioEngine
- [ ] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although Playground sends no WebSocket to AudioEngine
- [ ] Do underruns occur with CPUBurningSynth or AudioEngine 1.7, although Playground sends no WebUI stuff?

**Comment by MatthiasSeeber** [comment]
Would it be possible, that the general Memory Layout of the Audio Engine 1.7 may be compromised? It has grown since 1.5.

**Comment by hhoegelo** [comment]
We have to re-think the whole thing. Stephan had a "Geistesblitz": he remembered having glitches with 1.5 at namm show. Starting with this observation, we figured, that the assumption "but it works with 1.5" doesn't hold. There are no devices with hardware 5i3 and software 1.5 in the wild life.
1.5 software, so far, is only on devices with 7i3 - and on those tweaked by @AntonSchmied in America, which indeed may have glitch problem.

**Comment by nonlinear-labs** [comment]
I did some research:

- There are 8 units with a 5i3 and software version 1.5:
  - 1 unit (the 00035) that came back from Stanley Arts (for other issues) and now is under test by Henry
  - 4 units being in use for demos in L.A. (Tom Broderick, Dennis Hamm, Jacob Shea, ...)
  - 3 units have been delivered to customers recently (all located in Berlin)

- There is one unit with a 5i3 and the 1.7 NAMM preview at Paul Haslinger

We notices some glitches with units in L.A.

We might have missed the glitches of unit 00035 when it was refreshed, got the 1.5 software and was sent back to Stanley Arts, and also of the 3 units that we sold to customers. And these customers (+ Stanley) might not have complained about glitches because they havn't played much or do not listen very critical.

Unfortunately all units from 00001 to 00081 have the 5i3. This is more than I was aware. So there is a high demand for a solution for this type of ePC.

In addition we have three units with 5i3, running the current software version 1.7:
- 00001 at Matthias Fuchs
- 00005 at Matthias Seeber
- 00007 here in use by Thomas for sound design
All three show glitches.

**Comment by KlausStrohhaecker** [comment]
Random idea, do we use a lot of dynamic libraries? In the worst case (depending on library system architecture) a library function call would cause an exception which then loads the code from disk to memory first before execution can proceed. And after some time, the OS might decide the library isn't much in use and may unload it again from memory. Most probably linux doesn't operate like that, but there are/were some OS's which behaved exactly like that...

**Comment by KlausStrohhaecker** [comment]
Any chances to analyse kernel scheduling with tools like "perf" (http://www.brendangregg.com/blog/2017-03-16/perf-sched.html)?
As usual, a linux system is bloated with tons of utilities ans system programs but the ones that are needed in an emercency case are always missing :-)

**Comment by schlenkibus** [comment]
I think this ticket can be closed, as #1789 was merged
