### ISSUE TITLE
HWUI: Beim Umschalten des Ribbon-Modes von "Non-Return" auf "Return-to-Center" fehlt ein Update der LEDs. s.u.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1926]
Statt der aktuellen Position des verbundenen MCs wird Null (alle LEDs aus) angezeigt. Mit einer Bewegung des MCs wird die Ribbon-Anzeige dann aktualisiert.

**Comment by KlausStrohhaecker** [comment]
Ich denke "das muss so", zumindest in meiner quasi topaktuellen Version des PG (2020-06-02 19:38).

Nur wenn man das Ribbon bedient zeigt es eben die Bedienung an (abs oder rel, bei rel ist noch ein kleiner bug**), und wenn man es loslässt springt es auf Mitte, eben return-to-center. Der Wert des MC wird relativ zum Output veändert, und springt beim loslassen ebenso wieder zurück. Der MC-Wert wird "by design" niemals angezeigt im Ribbon.

**) wenn man von abs auf rel umstellt, ist der startwert von dem rel ausgeht nicht mitte, sondern null, erst wenn man das ribbon das zweite mal berührt stimmt es. Return-to-center + rel bedeutet ja, dass der tempärer shift eben bei Null losgeht, egal wo man auf dem Ribbon anfängt zu fahren, während bei abs auf die position gesprungen wird und die differenz zu mitte gleich verwendedt wird.

**Comment by hhoegelo** [comment]
Seems to be implicitly fixed by ribbon LED update bug: https://github.com/nonlinear-labs-dev/C15/commit/66902bc5e3b30493f1630038df6bacd23b4e8f4b
