### ISSUE TITLE
LPC dead on start 

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1953]
After updating a C15 with HW 6 with master - 381eb19 the LPC does not start as usual. One has to reset it manually. Similar behavior has been observed on a C15 with HW 7.1 when updating to KSTR-PedalUI. One had to restart the C15 twice after the update. Otherwise there was no sound.
 
I am "standing on the hose" atm. ... the only difference I see, is the reduction of LPC blobs to one.

**Comment by KlausStrohhaecker** [comment]
Root cause of the blocked LPC has been identified:
- Delay function in Clock Setup was ineffective (was optimized out)
- Some required setup delays in the Clock Setup procedure might not have been sufficient

Seems this has been on the edge from day one and now it finally broke.

==> Issue is about to close soon

Nonetheless,  a software reset of the LPC after power-up still seems to be required because the hardware reset + supply voltage ramp isn't fully on spec, electrically so the crystal oscillator may not start up 100% reliably. After a reset when power is fully up, it does.
