### ISSUE TITLE
Load toPart inconsistency if MCs have been changed

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2029]
The parameters of the into the part loaded parameters differ dependantly to previously changed MCs
That issue happens in both :  HWUI and in WEBUI (selection in Bank, or dragging) . 
Different settings of _direct load_ , _load to part_  have no influence.

1. start with layered Preset.
2. load anything into part I which uses **MC-B**
3. modulate MC-B to **0***
4. load NL Piano 14  007 _Till EP_ into **Part II**
5. have a look into Parameter settings of  _Allpass - Tune_ from **Part II**
![grafik](https://user-images.githubusercontent.com/4758563/85941938-686b9c00-b926-11ea-9e43-53d2bed78ef1.png)
6. modulate MC-B to **100**
7. load again NL Piano 14  007 _Till EP_ into **Part II**
![grafik](https://user-images.githubusercontent.com/4758563/85942108-7f5ebe00-b927-11ea-842f-68dd1f5952fb.png)

**Comment by MatthiasSeeber** [comment]
I can see that this feels inconvenient, but the observed effect is a logical consequence of the "Load To Part" mechanism and is in fact what should happen, at least according to the underlying concept so far.

There are **global** parameters like HW Sources, Macro Controls as well as Master Vol/Tune and Scale, which are present only once in a preset (regardless of its sound type: single/split/layer). When loading into a Part, the global HW Sources and Macros are _ignored completely_ - otherwise, you would observe the described situation in your **Part I**, which would be even more confusing. So, you have to keep in mind that there are some limitations of loading stuff into a Part.

I'm aware that our documentation does not sufficiently explain the "Load to Part" mechanism in exquisit detail (which could be a little overwhelming..) - so far, our "Manual Addendum"  tells this about the **parameter organization**:

![ParamOrga](https://user-images.githubusercontent.com/37212609/85943683-d7022700-b931-11ea-8c21-5792a7dac831.png)

So at least there already is a hint that HW Sources and Macros will not be loaded to Parts, but specific details are not mentioned. But as I said, the details can be overwhelming. If you want to go down the rabbit hole and have a look at each "Convert to" or "Load to" scenario and what happens to specific parameters, you may want to have a look at our (internal) **Conversion Rules** document:

[ModeConversionRules_Rev6.zip](https://github.com/nonlinear-labs-dev/C15/files/4842004/ModeConversionRules_Rev6.zip)

If you have suggestions on how to communicate those processes more effectively to the user, feel free to express them.

**Comment by majjam** [comment]
thanks for the explanation. i have to think about my answer after reading the conversion rules.

**Comment by majjam** [comment]
[loud thinking ]What i do understand and completely agree with is that the hardware assignments and adjusted amounts are seen globally on conversion to a layer/split preset. Of course those settings have to apply for both parts.
On the other hand it is allowed to have different amounts of assigned MCs at the the same parameters for different parts.
part I : pitch-A MC-B mc-amount 20 (converted to layer)
part II : pitch-A MC-B mc-amount 25 (loaded into layer)
If the HW setting of MC-B on both presets is equal i expected to find the mc-amount and base position of part II like in the source preset.( I see that we run into trouble if the MC-B setting differs.)

The problem I faced was mainly depending on the position of my Pedals while I was loading the preset into part.
That position differed from the saved value in the preset.

Maybe an addition to the manual like following text could be a helpful.

"**Loading into part** :
_While loading a present into part make sure that all modulation hardware (ribbons, pedals, pitch bender, cv) are in the same position as it was saved in the source preset. The easiest way to achieve that is have the source preset previously saved with all modulator hardware in a certain position.
You can later use the compare function in the web interface to have a more detailed view at possible differences._"

**Comment by MatthiasSeeber** [comment]
Okay, thanks for the description and docu suggestion!

I agree that at the moment, it would be a good idea to stress to the user that modulation shall not be touched until having finished assembling Parts together, otherwise assignments get messed up easily. Or at least, all non-returning sources should stay the same during Load to Part - returning Sources should work I think, given that they have returned back to zero when loading something.

I'm afraid there is no workaraound for the non-returning Sources, though. I just considered if maybe some kind of "Soft Takeover" approach could be able to resolve this, but since the Macros are also global, this would have to be done for each parameter in each part individually. And even then, I have no idea if this would be benefitial, or even more confusing - to be honest.

**Comment by majjam** [comment]
old and invalid ticket- > close
