### ISSUE TITLE
[Enhancement] OLED screen saver [priority low]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2031]
Probably it makes sense to have a screen saving feature for the OLEDs. Espicially for studio situations where you wait for things.
If i use the screen test mode on my unit, i can see degenerated dots/lines on both displays.  Kind of inverse in-burnings
Of cause my unit has lots of workinghours so far..

I recommend following
- Device setting for screen saver time in minutes 0-20 (0 means feature is deactivated)
- Wake up should be triggered by accessing one of all of the HW sources :  Pitchbender, Pedal Input, Key input, Panel buttons...

- Eventually a dimming settings for the soled ?

Hard to see on that foto, but for the files..
![grafik](https://user-images.githubusercontent.com/4758563/85943221-ecc21d00-b92e-11ea-81bf-65cc1072e1a9.png)

**Comment by KlausStrohhaecker** [comment]
This is on the back-log already. We are running both OLEDs at max intensity in the hardware and some sort of screen-saving would be nice for 24/7 duty.

The small OLED is B/W only, so no way of dimming, but a moving banner "NLL ~C15" would do.

Wake-Up, when triggered by a button (or encoder button/rotation), should ignore the button press and wait for the release (or encoder stable for more than ~0.5s), functionally.

Pedals and Bender are easily triggered by vibrations so I'd restrict the wake-up on keybed events, ribbon events and any UI action (also via Web-UI)

IHMO shorter inactivity times than 30min make little sense, I would suggest 3 choices for the settings OFF, 30min, 2hours.

**Comment by majjam** [comment]
Fully agreed

**Comment by majjam** [comment]
As I see that on the screensaver feature is worked on, I want to bring the attention not only to the oleds but also to the red leds of the panel unit and ribbon bars:

i would recommend to 
- disable all OLEDs (top and botton)
- disable all Panel LEDS and 
- use the Ribbon Leds for a running light (nothing to crazy)

With this you have an indicator that C15 is in standby mode even if panel unit is detached.
On the other hand you have minmal acitvely lighting components which can degrade.


Wakeup :
- Keybed events,
- Bottom units buttons
- Panel units buttons and encoder

(I personally prefer complete black displays against moving logos ..)

**Comment by KlausStrohhaecker** [comment]
As of now, the screen-saver basically is working.

I feel there are still issues with the different states, notably the discarding of the user input that  exits screen-save mode.

#### That's what I have in mind:
- There are two basic states, screen-saver **inactive** ("normal state") and screen-saver **active**.
- During the transition from active to inactive screen-saver the **user action which triggered the wakeup should be discarded**.

#### 1) In **inactive** state, the timeout monoflop shall be retriggered by the following events:
- Press or Release event of any of the buttons (incl. Encoder-Button), or
- Update event from Rotary Encoder, or
- Any update event from any of the hardware sources (0...12, 12 sends the last keybed press, see https://github.com/nonlinear-labs-dev/C15/blob/unstable/projects/shared/playcontroller/playcontroller-defs.h).


#### 2) Active screen-saver state is entered when the timeout has fully elapsed. 
Then, the following events shall exit active mode:
- Any update event from any of the hardware sources (0...12). The event itself shall not be discarded.
- Or, any Press or Release event of any button (incl. Encoder) and any Encoder activity. Here, these and any further events shall be discarded until the user action to "wake up the C15" is fully over, that means until all buttons are in released state for 500ms or so **and** there was no encoder changes within the last 500ms or so (exact times to be determined experimentally, 500ms might be a bit to long, actually).
- Or, any detach/attach event of the panel unit (the connection status of the panel unit can be polled by the ESPI_buttons driver, see https://github.com/nonlinear-labs-dev/C15/blob/unstable/projects/bbb/espi-driver/espi_buttons.c).
- Normally, WebUI activity shall **not** exit screen-save mode but it might be nice to have a developper switch to allow this trigger as well (also for a monoflop retrigger, see above).

[It's probably wise to apply a timeout to the wakeup action, too, like 3 seconds or so after which the wait for "all released" is aborted. It happens from time to time that a button gets stuck from improper alignment of the magnet foils and this would otherwise brick the UI when screen-saver comes on with the UI having seen the press event of the stuck button before]

By this, pressing arbitrary buttons (one might hit two at once in fast movement) will never result in parameter/state changes, notably not dangerous things like confirming a delete and such. Encoder actions also would not come through uncontrolled.

----------- 

Further notes:
- The screen-saving pattern on the SOLED could also be the fully "wandering string".
- I suggest using log-spaced list of timeout intervals: 1m, 5m, 20m, 1h, 3h, never(=off).
