### ISSUE TITLE
Shifting pitch on the play panel

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2090]
In order to shift the pitch semitone-wise one has to hold down + or - and tap the other, which works just fine.
However, if you want to switch the shift direction you must let go of both buttons. Keeping the last tapped button pressed and tapping in the "other direction" does not shift the pitch. It furthermore disables the shift reset to 0.

Not sure, but is this a LPC matter?

**Comment by KlausStrohhaecker** [comment]
LPC is not at all involved here.

On the other points, I would agree, the stepping process is already a bit awkward and it would be nice to have a clean/constistent behavior here. Also, some hints on the display what is going on would be nice. Sort of quick-help type of thing, mouse-over style. Otherwise most users won't even notice it that you can step in semitones also and have a reset, unless they thoroughly read the manuals (which most people don't). These basic functions/features should be self-documenting, IMHO.

**Comment by MatthiasSeeber** [comment]
> [...] Also, some hints on the display what is going on would be nice. Sort of quick-help type of thing, mouse-over style. Otherwise most users won't even notice it that you can step in semitones also and have a reset, unless they thoroughly read the manuals (which most people don't). These basic functions/features should be self-documenting, IMHO.

- this is a Base Unit-exclusive feature currently, meaning that there is no other representation of that setting (neither BOLED nor WebUI)
- regarding consistence: as the Base Unit can be used on its own, the SOLED should suffice displaying any possible help, which may be hard to do because of the small dimensions and already quite filled space
- anyhow, the SOLED +/- buttons depend on the MODE, and only in Default or RibbonEditor modes, they trigger transposition (in Preset or Bank mode, they select respectively)
- so, if the user is in the Default or RibbonEditor SOLED mode, the SOLED already reflects the changing transposition by displaying changes to the value (the update happening, when a button is released)

Regarding the flaw with maintaining the transpose direction as described above I would guess that this could be fixed.

Regarding additional user help in the small SOLED, I am not sure if there could ne anything done. I deem it rather difficult to deduce a "transpose semitone" or "transpose reset" context, dealing with only two binary states, button-release event logic and button-press timer logic (for reset).

**Comment by KlausStrohhaecker** [comment]
I mean something as simple as a popup "press (+) for semitone shift" (top line) and "hold both for reset" (bottom line), during the time (-) is pressed (after a short delay). Vice versa when (+) is pressed. Long text can be made visible by shifting it one pixel every 500ms or so. I for one didn't realize for more than a year that semitone shifts where possible at all because there were no real-time hints to that. I had read the manual once but it didn't stick... 

Same thing with the switchover of the meaning of the mode and funct buttons when pressed longer.

**Comment by MatthiasSeeber** [comment]
Let's conceptualize the following: every one of the four buttons has a press and a release event. Furthermore, each button has a hold phase - that should fit describing the current implementation.

The trigger behavior of a button can depend on the current Mode (as for +, -, Funct - sometimes listening to press, sometimes listening to release events). Furthermore, when a button enters the hold phase, this can additionally trigger something (like for the Mode button).

So I see no truly consistent way of exploiting the hold phase of a button, unless we split the hold phase into two stages:
1. If a button is held for long enough, an Info screen may be shown.
2. if the button is held for even longer. an action can be triggered and any Info screen shall be closed.

If the info screen needs to scroll in order to display its full content, this may be problematic, as this would delay the stage 2.

Nevertheless, here is a brief concept showing the current logic and additionally possible info screens for the soled - marked in red:

![Soled_Concept_Info](https://user-images.githubusercontent.com/37212609/88833320-5fdedd80-d1d2-11ea-8362-39acb2612870.png)

**Comment by MatthiasSeeber** [comment]
Update:
- the original problem (being able to change the Note Shift direction without having to release a button first) should not be that hard to implement and can be tackled
- further thoughts on a context info mechanism for the Soled may or may not be developed and addressed in the future, for now this is only subject of enhanced documentation
