### ISSUE TITLE
Fix Acceptance-Test VoiceAllocation -> Should the Level really be Above 0.5?

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2575]
How is this Feature supposed to function, do parameters/types of the current and next loaded preset play a role if the notes will re-trigger or stay?

Scenario:
Voices remain if old Type == new Type && old unisonVoices == new unisonVoices && old monoEnable == new monoEnable
+ Envelope + Comb can also have impacts on this

maybe use gate signal as Matthias suggested

**Comment by MatthiasSeeber** [comment]
Impacts can also be: Sustain and Level Parameters, Part Mute and other extreme conditions.

In #2576 I provided a new Acceptance Tester for the AudioEngine, capable of obtaining the "active" Voices of the C15. This should suffice to perform `SCENARIO("Voices remain on preset change")`, given the following circumstances.

A Reset happens when:
- specific changed Parameters **Unison Voices**, **Mono Enable** (in Preset or Parameter Message)
- received Preset Message: next to Unison and Mono change, a Reset occurs when the Sound Type differs (Preset Glitch Suppression DOES NOT affect this)
- received MIDI Setting Message from Playground
