### ISSUE TITLE
Upload and install Update via WebUI

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C15#2596]
this can be useful for devices with broken USB

**Comment by majjam** [comment]
upload via Webui could be really comfortable, but if plaground crashes for any reason, too then ssh is the last chance

So an alternative could be an emergency pack with some instructions and a script - because the update possibility via wlan is already there.

for windows something like  : 
1. install ssh (link to windows ssh install feature site like https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/)
2. place c15-update.cmd file and nonlinear-c15-update.tar together into any folder.
3. connect to C15 via wlan
4. start c15-update.cmd
5. do not switch off c15 unitl ready

windows c15-update.cmd :
del %homepath%/.ssh/known_hosts
ssh root@192.168.8.2 "rm -rf /update && mkdir -p /update" 
scp -C nonlinear-c15-update.tar root@192.168.8.2:/update 
ssh root@192.168.8.2 "cd /update/ && tar xf *.tar"
ssh root@192.168.8.2 "chmod +x /update/run.sh" 
ssh root@192.168.8.2 "/update/run.sh reboot"
 
i think linux users can do that themselves and for MACOS it could be analog to above instructions

**Comment by AntonSchmied** [comment]
we should also keep in mind, that once the ePC is the one to host Wifi, then we should build in a check to where the update.tar should be copied to!
