### ISSUE TITLE
Panel Unit: display for setting options is inconsistent

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#2641]
Setup -> Device Settings -> Sync Parts across UIs
Setup -> Hardware UI -> Screensaver Timout

These two settings only show the currently selected option, but not the available in comparison to other settings. 
Detected on Release 21-16

Plus, is it possible to set the following to these defaults, please:
Setup -> Device Settings -> Sync Parts across UIs: ON
Setup -> Device Settings -> Preset Glitch Suppression: ON
Setup -> Hardware UI -> Screensaver Timout: 5 Minutes

**Comment by majjam** [comment]
-> Preset Glitch Suppression: ON
Please don't  ;)
leave it to OFF
(subjective opinion )

**Comment by schlenkibus** [comment]
Preset Glitch Suppression is already being defaulted to 'on'. I am not going to touch it for now

**Comment by AntonSchmied** [comment]
@majjam please elaborate. ;)

**Comment by schlenkibus** [comment]
We determined the 'wrong' Default for PresetGlitchSuppression is not broken. Since July 2020 the setting defaults to "On". But due to the production process an older version of the Playground will be running briefly and saving the old defaults into an settings.xml. This Setting XML will then be read from the newest Playground and the newer defaults no longer appear to be active.

3 Possible Solutions:
1. Do not run the old 18-x PG in the production process (Anton said he could try to apply the initial update (18-x) and the newest update in the same boot cycle without starting the Playground first. This would prevent an older version from creating the xml file
2. remove settings.xml in production process: right before installing the final update the settings.xml could be removed and the old defaults with it. This could possibly lead to missing information like SSID?
3. Update the initial update: the 18-x update could be rebuild with the updated defaults for old settings. This way the first run of the PG would not lead to incorrect values in the XML. But i believe this is not sustainable as we would have to maintain an ancient version (build-wise)

My personal Opinion is that the production process should try to prevent the old/initial playground from running. If that is not possible the production should remove the old file before applying the newest update, if it is given that no data is lost

**Comment by majjam** [comment]
Sorry im a bit in a hurry so i will answer tomorrow more detailed.

**Comment by majjam** [comment]
OK now a bit more detailed answer : 

I (think i) know that the glitch supression is not directly related the sound transition feature but subjectively for me it is connected. At least for cineastic sound effects the glitching is a really interesting feature and can be even used musically. 
Especial now as it can be sequenced via midi. 
I know that is nothing the c15 is intended to, but compare those both snippets:
[Glitch ON Off.zip](https://github.com/nonlinear-labs-dev/C15/files/6503727/Glitch.ON.Off.zip)
You would not find these thing if it is set to OFF as default. 

Thats why i wrote 'PLEASE DON'T' ;) .

------------------------
related off-topic : 
In the first time when i had my C15 it was a bit weird when switching through the presets while playing.
But then i played around with the transition time and set it to high values (8000ms or so).
I did the same - switched through the presets  while playing on the keybed.
What i found out was that C15 is able to transform a sound incredibly deep - more than i thought before
This 'weird' sound transition behaviour leaded me to really have a look into the MCs and their assignments. 
In my opinion the pedal driven sound transformation possibilities of the C15 is one of the most noteworthy of its features. 

Thats why I always had one thing in mind regarding the **sound transition**: 
What would be if you could stop the transition at a point and play at this point as long as you want and then generate a new preset out of it ?
Or what about assigning a pedal to the transformation between old an new preset to fast forward or rewind that effect ?
could be perhaps done in the new layer mode
- Preset morphing

ok now i shut up
