### ISSUE TITLE
MIDI-"All Notes Off" werden zu oft geschickt (s.u.)

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#2925]
Wenn man zwischen Single/Layer/Split/Mono/Nicht-Mono/Unison/Nicht-Unison-Presets wechselt (= Voice-Allocation-Reset), sollte über MIDI nur dann "All Notes Off" verschickt werden, wenn beim Presetwechel eine Taste gedrückt war.

**Comment by davidm2894** [comment]
Bei Wechsel von Nicht-Split auf Split wird weiterhin ein AllNotesOff geschickt, auch bei nicht gedrückter Taste, und zwar auf dem Primary Channel.

**Comment by davidm2894** [comment]
Nachtrag zum gleichen Vorgang: Wenn ich zunächst im im Split Preset in Part II eine Note halte und in ein Nicht-Split Preset wechsle und dann ohne Tastendrücken zwischen den beiden Presets hin- und herwechsle, dann schickt er beim rausgehen aus dem Split Preset auf dem Split Channel ein AllNotesOff und beim Wechsel auf das Single Preset ein AllNotesOff auf dem Primary Channel. 

Wenn ich **Panic** drücke, dann wieder nur so wie in meinem ersten Kommentar.

**Comment by MatthiasSeeber** [comment]
I tested thoroughly with the latest RC (see [4e820c0](https://github.com/nonlinear-labs-dev/C15/commit/4e820c04ed60d1a93a1aac424224e1fa80c60ef4)) and verified the following:
- [x] Recall with same Sound Type: AllNotesOff only when Keys are pressed and Unison or Mono changed (Split: per Part)
- [x] Recall with differing Sound Types: AllNotesOff only when Keys are pressed (_in the context of the **old** Sound Type_, Split: per Part)
- [x] Unison/Mono Parameter changes: AllNotesOff only when Keys are pressed (Split: per Part)
Otherwise, the "soft Holzhammer" applies for changing MIDI Settings (_Local, Channels, Routings_): if Keys are pressed, a Reset occurs internally and externally (AllNotesOff), regardless of the Sound Type
