### ISSUE TITLE
Pedal Presets: Pedal OFF inconsistencies?

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3017]
If a Pedal HW Source has the `Setup > Pedal Preset` "OFF", it will not react to the corresponding physical Pedal (even when the corresponding Pedal is connected). 

However:
- changing the Pedal Parameter via Web- or HW-UI is possible and starts a Modulation (visible and audible), there also is no visual distinction to Pedals !== OFF
- changing the Pedal Parameter via MIDI is possible and starts a Modulation (visible and audible)
- described changes will also be sent via MIDI

We could argue that this behavior is inconsistent and that such a Pedal should really be disabled (in UI and MIDI) alltogether.

We also could argue that this behavior is consistent and that the Pedal Preset only applies to the physical Pedal (PlayController):
- in the UI, all Sources are displayed and thus present
- for MIDI, all assigned Sources are present

So, which way to go? (This should also be mentioned in the User Documentation)

**Comment by majjam** [comment]
my 5 cents :

Pedal presets are applicable for the physical HW-Inputs. 
The setting OFF is for avoiding floating values from the pedal inputs.
Other settings aren't applied to midi and webui neither,(correct me if im wrong - or do we have different calibration curves here ?)
In my opinion the rest : webui midi and so on can be untouched.

=> The second argument - pedal presets are for physical inputs only -feels right to me.

**Comment by KlausStrohhaecker** [comment]
> The setting OFF is for avoiding floating values from the pedal inputs.

Actually, it is also for explicitly turning off a pedal globally.

I think the behavior is consistent as per argument two. Enabled pedals which do not move also never send a value but yet the "logical pedal" connected to it can be changed/overridden via UI or MIDI... until the pedal is moved again.
This is the effect of any event-based messaging system, we do not distinguish between two logical cases of non-events: pedal detached or assigned OFF vs no pedal change is the same non-event for us.

I would agree that it might make sense to graphically mark an OFF pedal source somehow. The PG knows this and it could prevent the user from having issues with seemingly "non-working pedals" because he/she forget to check for OFF status.

**Comment by nonlinear-labs** [comment]
Ok, ich mache ein anderes Ticket auf für eine OFF-Marke an den Pedalen in der UI.
