### ISSUE TITLE
Should bidirectional Ribbon send MIDI when changed by MC?

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#3059]
Consider the typical Ribbon use case: NonReturn, connected to exclusively one Macro Control.

When the Ribbon itself is changed (by a touch gesture on the led strip, or by editing the ui parameter), MIDI will be sent.

When the corresponding Macro Control is changed (by editing the ui parameter or by additional f.e. Pedal modulation), the Ribbon will change as well (due to the bidirectional linking of non-returning Ribbons).

Now here's the question: should MIDI be sent for the changed Ribbon in these cases?

**Comment by davidm2894** [comment]
I would say no. 

All MIDI connections and transfers are bind to the hardware sources not to the Macro Controls. This implies (in my opinion), that MIDI is being sent only when the actual source is touched, which would not be the case when it changes due to bidirectional linking. 

Also, when MIDI would be sent, this could lead to problems when using the C15 as a MIDI-Masterkeyboard. Parameters could be changed unintentionally. 

Example.:

Pedal 1 -> Connection to -> Parameter 1 of external device
Ribbon 1 -> Connection to -> Paramter 2 of external device
Pedal 1 is moved -> Parameter 1 and 2 change

I would say that this behavior is unwanted in most scenarios.

**Comment by MatthiasSeeber** [comment]
I think you're right. It seems
1. not necessary: internally, every state is reproducable - even when using recorded MIDI to reproduce
2. potentially problematic (as you already described)
