### ISSUE TITLE
Flanger-envelope only works on 12 voices

### ISSUE THREAD

**Issue by Oni030** [nonlinear-labs-dev/C15#3780]
**Description**
The Flanger-envelope works for 12 voices, then stops working for 12 voices until it starts working again for 12 and so on and so forth.

**BOLED or WebUI**
Neither

**C15 Software Version as found in systeminfo**
Branch: 23-17 main
HEAD: 9760b18f2

**To Reproduce**
1. Pick a preset without Flanger
2. Flanger Rate to ≈5Hz
3. Flanger Envelope to 100%
4. Flanger Time Mod to 100%
5. Flanger Mix to 100%
6. Play 24 Notes

**Expected behavior**
Envelope works for all voices.

**Comment by MatthiasSeeber** [comment]
Good catch.

I'm highly confident that this bug arises as follows:

- we have two Polyphonic Sections (Env ... Mix, with 12 Voices each) as well as two Monophonic Sections (FX), regardless of the Sound Type
- if a Polyphonic Section registers a KeyDown, the corresponding Monophonic Section will register this KeyDown as well (and start the Flanger Env), but only when no prior keys are already pressed
- we also have the capability to send output of the Polyphonic Section two both Monophonic Sections (Out Mix > To FX)
- if output of a Polyphonic Section is sent to the **other** Monophonic Section, the corresponding Flanger Env will never by triggered (as this only affects the **corresponding** Monophonic Section)

So, buggy behavior is expected to occur with:
- Single Sounds: both Polyphonic Sections will be sent to the Monophonic Sections according to the Out Mix > To FX (typically 100% to FX I), but only pressed Keys within Poly I will trigger Mono I (quasi at random, depending on the Voice Allocation)
- Split Sounds: sending to the other FX will never start the Flanger Env there
- (Layer Sounds should be fine due to identical voices in both Parts)

A potential solution would be to not count active keys for each Polyphonic Section, but globally instead. But this would break with current behavior. The other (more sophisticated) approach would be to evaluate the Out Mix > To FX parameters in order to know which Monophonic Section to trigger.
