### ISSUE TITLE
WebUI: Fade indicators can be clicked

### ISSUE THREAD

**Issue by davidm2894** [nonlinear-labs-dev/C15#3784]
**Describe the bug**
The fade indicators in the soundtab, which show if a key fade is present in a particular part, can be clicked and change their display while pressed. However, this has no actual effect. If the keyboard is not completely assigned to both parts (fade symbol), then the symbol changes permanently after pressing (at least until the other part is selected, which sets the indicators to their correct status). 
<img width="766" alt="Bildschirmfoto 2023-06-06 um 14 05 29" src="https://github.com/nonlinear-labs-dev/C15/assets/84857645/d7979382-15a8-4077-af92-c71980885688">

**BOLED or WebUI**
WebUI

**C15 Software Version as found in systeminfo**
23.10
348589db3a

**Expected behavior**
The indicators should not respond to click/touch.

**WebUI Metadata (please complete the following information):**
 - OS MacOS/iPad OS
 - Chrome/Safari
 (but should not be related to)

Edit: Changed keybed indicators to fade indicators.

**Comment by MatthiasSeeber** [comment]
I can confirm the described bug (23.13) and agree that the indicators should not respond to click/touch - but would like to ammend:

1. :information_source: I'd prefer to call those "Fade Indicators", indicating if a Key Fade is present (Fade From != default). In Layer Sounds, key assignments are equal for both Parts and every key is processed, even if its fade level is zero.
2. :question: Is it intentional, that the Boled does not show "flat" indicators, unlike the WebUI? _("flat": no fade, Fade From == default, indicator is horizontal line)_
3. :bulb: there is a potential use case for having the fade indicators in the WebUI react to double clicks: if a fade is present, it could be quickly defaulted, instead of having to focus on the fade editor or fade parameters. In this case, the fade indicator should change into its "flat" state.

**Comment by davidm2894** [comment]
> I can confirm the described bug (23.13) and agree that the indicators should not respond to click/touch - but would like to ammend:
> 
> 1. ℹ️ I'd prefer to call those "Fade Indicators", indicating if a Key Fade is present (Fade From != default). In Layer Sounds, key assignments are equal for both Parts and every key is processed, even if its fade level is zero.

Changed the naming.

> 2. ❓ Is it intentional, that the Boled does not show "flat" indicators, unlike the WebUI? _("flat": no fade, Fade From == default, indicator is horizontal line)_

That's true. Haven't noticed it yet and I would assume that it's not intentional, @nonlinear-labs?

> 3. 💡 there is a potential use case for having the fade indicators in the WebUI react to double clicks: if a fade is present, it could be quickly defaulted, instead of having to focus on the fade editor or fade parameters. In this case, the fade indicator should change into its "flat" state.

Actually not a bad idea, this could be useful.

**Comment by MatthiasSeeber** [comment]
Update: it IS intentional that in the Boled, there is no "flat" Indicator for default Fades.
